import Image from "next/image";
import Link from "next/link";
import { Arrow, ContactCta, Footer, Header, services } from "./components";

export default function Home() { return <main>
  <div className="hero-wrap"><Header/><section className="hero"><div className="hero-copy"><p className="eyebrow">AI · SOFTWARE · CLOUD · WEB3</p><h1>Build what&apos;s<br/>next. <em>Better.</em></h1><p className="lead">We design and engineer intelligent digital products—from AI agents and cloud systems to web platforms that move business forward.</p><div className="hero-actions"><Link href="/contact" className="button button-lime">Start a project <Arrow/></Link><Link href="/services" className="text-link">Explore capabilities <Arrow/></Link></div></div><div className="hero-image"><Image src="/images/engineering.jpg" alt="Software engineer working at a computer" fill priority sizes="(max-width: 760px) 80vw, 38vw"/></div></section><div className="ticker"><span>AI ENGINEERING</span><b>✦</b><span>PRODUCT DEVELOPMENT</span><b>✦</b><span>CLOUD INFRASTRUCTURE</span><b>✦</b><span>BLOCKCHAIN</span></div></div>
  <section className="intro section"><div><p className="eyebrow">What we believe</p><h2>Technology is only powerful when it makes <em>work feel lighter.</em></h2></div><div><p>That&apos;s why we pair sharp product thinking with serious engineering. We&apos;re here to make complex technology useful, reliable and ready for the real world.</p><Link href="/about" className="text-link dark-link">Meet ReferTech AI <Arrow/></Link></div></section>
  <section className="image-break"><Image src="/images/network.jpg" alt="Connected digital network" fill sizes="100vw"/><div><p className="eyebrow">Engineered for momentum</p><h2>Good ideas deserve<br/>a <em>working system.</em></h2></div></section>
  <section className="services-preview section"><div className="section-heading"><div><p className="eyebrow">What we do</p><h2>Deep expertise.<br/><em>One accountable team.</em></h2></div><Link href="/services" className="text-link">All services <Arrow/></Link></div><div className="service-grid">{services.map(([title,desc])=><Link href="/services" className="service-card" key={title}><div><Arrow/></div><h3>{title}</h3><p>{desc}</p></Link>)}</div></section>
  <section className="process section"><div className="process-label"><p className="eyebrow">How we work</p><h2>From signal<br/>to <em>scale.</em></h2></div><div className="steps">{[["Discover","Start with the business, the people and the opportunity."],["Design","Turn the right idea into a clear product and technical path."],["Deliver","Build in focused cycles, with visibility at every step."],["Evolve","Measure, learn and keep moving after launch."]].map(([n,d])=><div className="step" key={n}><h3>{n}</h3><p>{d}</p></div>)}</div></section>
  <ContactCta/><Footer/></main>;
}
